name: Scheduled Selenium Tests

on:
  schedule:
    # Run at 09:30 UTC (3:00 PM IST) Monday–Friday
    - cron: '30 9 * * 1-5'
  workflow_dispatch:   # <-- manual trigger to show in Actions UI & allow manual runs

jobs:
  test_and_generate_report:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest and generate HTML report
        run: |
          mkdir reports
          pytest --html=reports/report.html --self-contained-html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v3
        with:
          name: selenium-test-report
          path: reports/report.html
